/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class btc_oracle_core_wrapper_Script_network_type */

#ifndef _Included_btc_oracle_core_wrapper_Script_network_type
#define _Included_btc_oracle_core_wrapper_Script_network_type
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
