/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class btc_oracle_core_wrapper_Transaction_Output */

#ifndef _Included_btc_oracle_core_wrapper_Transaction_Output
#define _Included_btc_oracle_core_wrapper_Transaction_Output
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
