/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class btc_oracle_core_wrapper_Script */

#ifndef _Included_btc_oracle_core_wrapper_Script
#define _Included_btc_oracle_core_wrapper_Script
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     btc_oracle_core_wrapper_Script
 * Method:    address
 * Signature: (Lbtc_oracle_core_wrapper/Script/network_type;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_btc_1oracle_1core_1wrapper_Script_address
  (JNIEnv *, jobject, jobject);

/*
 * Class:     btc_oracle_core_wrapper_Script
 * Method:    segwit_address
 * Signature: (Lbtc_oracle_core_wrapper/Script/network_type;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_btc_1oracle_1core_1wrapper_Script_segwit_1address
  (JNIEnv *, jobject, jobject);

/*
 * Class:     btc_oracle_core_wrapper_Script
 * Method:    hash160
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_btc_1oracle_1core_1wrapper_Script_hash160
  (JNIEnv *, jobject);

/*
 * Class:     btc_oracle_core_wrapper_Script
 * Method:    hex
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_btc_1oracle_1core_1wrapper_Script_hex
  (JNIEnv *, jobject);

/*
 * Class:     btc_oracle_core_wrapper_Script
 * Method:    cleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_btc_1oracle_1core_1wrapper_Script_cleanup
  (JNIEnv *, jobject);

/*
 * Class:     btc_oracle_core_wrapper_Script
 * Method:    lockTime
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_btc_1oracle_1core_1wrapper_Script_lockTime
  (JNIEnv *, jclass, jint);

/*
 * Class:     btc_oracle_core_wrapper_Script
 * Method:    createSegwitDemandDeposit
 * Signature: (IILjava/util/ArrayList;II)Lbtc_oracle_core_wrapper/Script;
 */
JNIEXPORT jobject JNICALL Java_btc_1oracle_1core_1wrapper_Script_createSegwitDemandDeposit
  (JNIEnv *, jclass, jint, jint, jobject, jint, jint);

/*
 * Class:     btc_oracle_core_wrapper_Script
 * Method:    create_P2WPKH
 * Signature: (Ljava/lang/String;Lbtc_oracle_core_wrapper/Script/network_type;)Lbtc_oracle_core_wrapper/Script;
 */
JNIEXPORT jobject JNICALL Java_btc_1oracle_1core_1wrapper_Script_create_1P2WPKH
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
