/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class btc_oracle_core_wrapper_Transaction */

#ifndef _Included_btc_oracle_core_wrapper_Transaction
#define _Included_btc_oracle_core_wrapper_Transaction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     btc_oracle_core_wrapper_Transaction
 * Method:    create
 * Signature: (IILjava/util/ArrayList;Ljava/util/ArrayList;)Lbtc_oracle_core_wrapper/Transaction;
 */
JNIEXPORT jobject JNICALL Java_btc_1oracle_1core_1wrapper_Transaction_create
  (JNIEnv *, jclass, jint, jint, jobject, jobject);

/*
 * Class:     btc_oracle_core_wrapper_Transaction
 * Method:    cleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_btc_1oracle_1core_1wrapper_Transaction_cleanup
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
